//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        public long Id { get; set; }
        public int Numero { get; set; }
        public decimal MontoCredito { get; set; }
        public int NumeroCuota { get; set; }
        public int CuotasPendiente { get; set; }
        public decimal MontoCuota { get; set; }
        public decimal Saldo { get; set; }
        public string UltimoPago { get; set; }
        public decimal Atraso { get; set; }
        public decimal Pagado { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Pago { get; set; }
        public long CreditoId { get; set; }
        public long ClienteId { get; set; }
        public string Estado { get; set; }
        public int CodigoCredito { get; set; }
    
        public virtual Credito Credito { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
